sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t damiankrzeminski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true damiankrzeminski/react-test npm test

after_success:
  - docker build -t damiankrzeminski/multi-client ./client
  - docker build -t damiankrzeminski/multi-nginx ./nginx
  - docker build -t damiankrzeminski/multi-server ./server
  - docker build -t damiankrzeminski/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push damiankrzeminski/multi-client
  - docker push damiankrzeminski/multi-nginx
  - docker push damiankrzeminski/multi-server
  - docker push damiankrzeminski/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "Multi-Docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-058264342090"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
